"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./src/client.py']
# APP = []
DATA_FILES = ['./src/templates/','./src/static/','./src/config.py','./src/data.py','./src/setup.py','./src/widgets/','./src/prompt/','./src/dicts','./src/data/']
# DATA_FILES = []
OPTIONS = {
        'iconfile':'./res/intellifusion_sketch_1.icns',
        'plist':{
            'CFBundleName'   : 'Intellifusion',     # 应用名
                    'CFBundleDisplayName': 'IntelliFusion', # 应用显示名
                    'CFBundleVersion': '0.2.1',      # 应用版本号
                    'CFBundleIdentifier' : 'IntelliFusion', # 应用包名、唯一标识
                    'NSHumanReadableCopyright': 'Copyright © 2023 Argon.Inc. All rights reserved.', # 可读版权
            'includes': ['flask','flaskwebgui','jieba','loguru',
                        'openai','peewee','requests',
                        'thefuzz','validators','mistune']
                        },
             }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
